### ISSUE TITLE
Create new release v0.1.4

### ISSUE THREAD

**Issue by lmilleri** [k8snetworkplumbingwg/govdpa#18]
The latest commits have introduced a change in the library public interface.
It is recommended to tag a new release of the library as a first step to update all the SW components that make use of govdpa.

Also this release would offer the capability to create/delete vDPA devices
(see README.md for further details)

**Comment by amorenoz** [comment]
Sure, good idea. Renaming issue.

**Comment by amorenoz** [comment]
Done!
